# Generated by Django 5.2.6 on 2025-12-04 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=60)),
                ('costo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=30)),
                ('phone', models.CharField(default='00 00 00 00 00', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='Unknown', max_length=30)),
                ('matricula', models.CharField(default='00-000-00', max_length=7)),
                ('color', models.CharField(default='None', max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Service_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('emision_date', models.DateField()),
                ('delivery_Date', models.DateField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.clients')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.cars')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0.0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.clients')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.service_orders')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas_app.servicios')),
            ],
        ),
    ]
