# Generated by Django 5.2.6 on 2025-12-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='picture',
        ),
    ]
