# Generated by Django 5.2.6 on 2025-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas_app', '0002_remove_cars_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='client',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='servicio',
        ),
    ]
