# Generated by Django 5.2.6 on 2025-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas_app', '0003_remove_factures_client_remove_factures_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factures',
            name='sn',
            field=models.CharField(default='0000-0000', max_length=9),
        ),
    ]
