# Generated by Django 5.2.6 on 2025-12-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas_app', '0004_factures_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factures',
            name='monto',
        ),
    ]
