# Generated by Django 5.2.6 on 2025-12-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas_app', '0005_remove_factures_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
